spring.application.name=ESL
server.port=7165
app.base-url=https://esl.cscs-apps.com/esl
server.servlet.contextPath=/esl
# JWT
jwt.secret=${JWT_SECRET}

# Dragon ESL API
dragon.esl.base-url=${DRAGON_ESL_BASE_URL}
dragon.esl.username=${DRAGON_ESL_USERNAME}
dragon.esl.password=${DRAGON_ESL_PASSWORD}
dragon.esl.merchant-id=${DRAGON_ESL_MERCHANT_ID}