spring.application.name=ESL
server.port=8080
app.base-url=http://localhost:8080/esl
# JWT
jwt.secret=cscs-digital-price-tag-secret-key-2026

# Dragon ESL API
dragon.esl.base-url=http://www.dragonesl.com
dragon.esl.username=DG0358
dragon.esl.password=xzlongan@123
dragon.esl.merchant-id=1775639851383