version: '3.8'

services:
  backend:
    build:
      context: ./cscs-digital-price-tag
      dockerfile: Dockerfile
    container_name: cscs-backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: deployment

      JWT_SECRET: cscs-digital-price-tag-secret-key-2026

      DRAGON_ESL_BASE_URL: http://www.dragonesl.com
      DRAGON_ESL_USERNAME: DG0358
      DRAGON_ESL_PASSWORD: xzlongan@123
      DRAGON_ESL_MERCHANT_ID: 1775639851383

    ports:
      - "7165:7165"

    networks:
      - cscs-network

    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./cscs-digital-platform-ui
      dockerfile: Dockerfile
    container_name: cscs-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "5140:5140"

    networks:
      - cscs-network

networks:
  cscs-network:
    driver: bridge